server:
  port: 8060

spring:
  application:
    name: service-lancamento
  h2:
    console:
      enabled: true
      path: /h2-ui
  datasource:
    url: jdbc:h2:file:../databases/lancamentosdb
    driverClassName: org.h2.Driver
    username: sa
    password:  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

cqrs:
  read: ${READ_ENABLED:true}
  write: ${WRITE_ENABLED:true}

client:
  contas:
    baseUrl: http://localhost:8050

management:
  endpoints:
    enabled-by-defaults: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
